import { useState } from "react";
import { toast } from "sonner";
import api from "@/lib/api";
import { PageHeader, Icon } from "@/components/common/ui";
import { Button } from "@/components/ui/button";
import { Tabs, TabsList, TabsTrigger } from "@/components/ui/tabs";

const starters = {
  cpp: "#include <iostream>\nusing namespace std;\n\nint main() {\n  cout << \"Hello, SmartLearn!\\n\";\n  return 0;\n}",
  java: "public class Main {\n  public static void main(String[] args) {\n    System.out.println(\"Hello, SmartLearn!\");\n  }\n}",
  python: "def main():\n    print(\"Hello, SmartLearn!\")\n\nif __name__ == \"__main__\":\n    main()",
};
const labels = { cpp: "C++ 17", java: "Java", python: "Python 3" };

export default function CodeLab() {
  const [language, setLanguage] = useState("cpp"), [code, setCode] = useState(starters.cpp), [input, setInput] = useState(""), [result, setResult] = useState(null), [running, setRunning] = useState(false);
  const chooseLanguage = (next) => { setLanguage(next); setCode(starters[next]); setResult(null); };
  const run = async () => { setRunning(true); setResult(null); try { const { data } = await api.post("/compiler/run", { language, code, input }); setResult(data); } catch (error) { toast.error(error?.response?.data?.error || "Could not run the program"); } finally { setRunning(false); } };
  return <div className="min-h-[calc(100vh-9rem)]"><PageHeader eyebrow="Practice workspace" icon="terminal" title="Code Lab" subtitle="Write, compile and run C++, Java and Python in one focused workspace." actions={<Button onClick={run} disabled={running}><Icon name={running ? "loader-2" : "play"} className={running ? "mr-2 h-4 w-4 animate-spin" : "mr-2 h-4 w-4"} />{running ? "Running" : "Run code"}</Button>} />
    <div className="rounded-2xl border border-streak/25 bg-streak/5 p-4 mb-5 text-sm flex gap-3"><Icon name="shield-check" className="h-5 w-5 text-streak shrink-0" /><span>Programs run with strict size and time limits. Use this for learning and test code only—never paste passwords, tokens or private data.</span></div>
    <Tabs value={language} onValueChange={chooseLanguage}><TabsList className="mb-4"><TabsTrigger value="cpp"><Icon name="code-2" className="mr-2 h-4 w-4" />C++</TabsTrigger><TabsTrigger value="java">Java</TabsTrigger><TabsTrigger value="python">Python</TabsTrigger></TabsList></Tabs>
    <div className="grid lg:grid-cols-[1.55fr_.85fr] gap-5"><section className="card-surface overflow-hidden"><div className="flex justify-between items-center px-4 py-3 border-b"><span className="font-mono text-xs text-muted-foreground">main.{language === "cpp" ? "cpp" : language === "java" ? "java" : "py"}</span><button onClick={() => setCode(starters[language])} className="text-xs text-primary">Reset starter</button></div><textarea spellCheck="false" value={code} onChange={(e) => setCode(e.target.value)} className="h-[500px] w-full resize-none bg-[#09111f] p-5 font-mono text-sm leading-6 text-slate-100 focus:outline-none" /></section><div className="space-y-5"><section className="card-surface overflow-hidden"><div className="px-4 py-3 border-b font-semibold text-sm flex gap-2 items-center"><Icon name="keyboard" className="h-4 w-4 text-primary" /> Standard input</div><textarea value={input} onChange={(e) => setInput(e.target.value)} placeholder="Optional input, one value per line…" className="h-32 w-full resize-none bg-background p-4 font-mono text-sm focus:outline-none" /></section><section className="card-surface overflow-hidden"><div className="px-4 py-3 border-b font-semibold text-sm flex items-center justify-between"><span className="flex gap-2 items-center"><Icon name="terminal" className="h-4 w-4 text-success" /> Output</span>{result && <span className={result.error ? "text-destructive text-xs" : "text-success text-xs"}>{result.timedOut ? "Timed out" : result.stage === "compile" ? "Compile result" : "Finished"}</span>}</div><pre className="min-h-56 whitespace-pre-wrap break-words bg-[#09111f] p-4 font-mono text-xs leading-6 text-slate-100">{result ? (result.error ? `${result.output || ""}${result.output && "\n"}${result.error}` : result.output) : "Run your code to see output here."}</pre></section><section className="card-surface p-5"><h2 className="font-display font-semibold">Today’s C++ drill</h2><p className="text-sm text-muted-foreground mt-1">Read n numbers and print their sum. Then change it to find the maximum.</p><Button variant="outline" className="w-full mt-4" onClick={() => { chooseLanguage("cpp"); setCode("#include <iostream>\nusing namespace std;\nint main() {\n  int n, x, sum = 0;\n  cin >> n;\n  while (n--) { cin >> x; sum += x; }\n  cout << sum << '\\n';\n}"); setInput("5\n4 8 15 16 23"); }}>Load challenge</Button></section></div></div></div>;
}
