import { useEffect, useState } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { useParams, Link } from "react-router-dom";
import { toast } from "sonner";
import api from "@/lib/api";
import { Icon, Loader } from "@/components/common/ui";
import { Button } from "@/components/ui/button";
import { Progress } from "@/components/ui/progress";
import { Badge } from "@/components/ui/badge";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { cn } from "@/lib/utils";

const typeIcon = { reading: "book-open", video: "play-circle", note: "sticky-note", quiz: "list-checks" };
const hints = {
  "Arrays & Hashing": ["Store prior values or frequencies, then use immediate lookup instead of comparing every pair.", "Walk left to right. Check the map/set before adding the current value.", "Target O(n) time and O(n) space."],
  "Two Pointers & Sliding Window": ["Keep only a valid range. Move each pointer forward once instead of restarting work.", "Expand right; if invalid, move left until the condition is true again.", "O(n) time; usually O(k) space for window state."],
  "Binary Search": ["Define a true/false condition that lets you discard half of the answer space.", "Write lo, hi, mid and say why the rejected half can never contain the answer.", "O(log n) checks; often O(n log range) for answer-space search."],
  "Trees & Graphs": ["Use DFS to explore branches and BFS for layers or shortest unweighted paths. Mark visited nodes.", "Draw the queue or recursion stack after each visit; never re-visit a node.", "O(V + E), or O(n) for a tree."],
  "Dynamic Programming": ["Define the smallest reusable subproblem, base case, and transition before coding.", "Calculate a tiny table by hand and confirm which earlier state builds each answer.", "O(states × transitions); optimise memory only after the recurrence is correct."],
};
const embed = (url) => { const id = url?.match(/[?&]v=([^&]+)/)?.[1] || url?.match(/youtu\.be\/([^?&]+)/)?.[1]; return id ? `https://www.youtube-nocookie.com/embed/${id}?rel=0` : ""; };

function Workspace({ topic, enrolled, complete, done }) {
  const notesKey = `smartlearn:notes:${topic._id}`, solvedKey = `smartlearn:solved:${topic._id}`;
  const [notes, setNotes] = useState(""), [solved, setSolved] = useState([]), [immersive, setImmersive] = useState(false);
  useEffect(() => { setNotes(localStorage.getItem(notesKey) || ""); try { setSolved(JSON.parse(localStorage.getItem(solvedKey) || "[]")); } catch (_) { setSolved([]); } }, [notesKey, solvedKey]);
  const hint = hints[topic.title] || ["Restate the input, output and constraints. Replace the repeated expensive operation with an appropriate pattern.", "Use the smallest non-trivial example and track every variable after each operation.", "State both time and space complexity, including stored helper data."];
  const toggle = (url) => { const next = solved.includes(url) ? solved.filter((x) => x !== url) : [...solved, url]; setSolved(next); localStorage.setItem(solvedKey, JSON.stringify(next)); };
  const video = embed(topic.resourceUrl);
  return <section className={cn("lesson-panel card-surface mt-6 overflow-hidden", immersive && "fixed inset-0 z-50 m-0 overflow-y-auto rounded-none bg-background")} data-testid="lesson-panel">
    <div className="lesson-panel__head p-5 sm:p-6 flex flex-wrap items-start justify-between gap-3"><div><div className="flex gap-2 text-primary text-sm font-semibold mb-2"><Icon name={typeIcon[topic.type] || "book-open"} className="h-4 w-4" /> Interactive lesson</div><h2 className="font-display text-2xl font-bold">{topic.title}</h2><p className="text-sm text-muted-foreground mt-2">{topic.durationMin} minute focus block · learn, reason, practise, reflect.</p></div><div className="flex gap-2"><Badge variant="outline">{topic.practiceLinks?.length || 0} practice questions</Badge><Button size="sm" variant="outline" onClick={() => setImmersive(!immersive)}><Icon name={immersive ? "minimize-2" : "maximize-2"} className="mr-1.5 h-4 w-4" />{immersive ? "Exit" : "Focus"}</Button></div></div>
    <div className="p-4 sm:p-6"><Tabs defaultValue="learn"><TabsList className="w-full justify-start overflow-x-auto"><TabsTrigger value="learn">Learn</TabsTrigger><TabsTrigger value="understand">Logic & dry run</TabsTrigger><TabsTrigger value="practice">Practice {solved.length ? `(${solved.length})` : ""}</TabsTrigger><TabsTrigger value="notes">My notes</TabsTrigger></TabsList>
      <TabsContent value="learn" className="mt-5 space-y-5">{video && <div className="aspect-video overflow-hidden rounded-xl border bg-black"><iframe title={`${topic.title} video`} className="w-full h-full" src={video} allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowFullScreen /></div>}{topic.resourceUrl && !video && <a href={topic.resourceUrl} target="_blank" rel="noreferrer"><Button variant="outline">Open learning resource <Icon name="arrow-up-right" className="ml-2 h-4 w-4" /></Button></a>}<article className="rounded-xl bg-muted/60 border p-4 sm:p-5 whitespace-pre-wrap leading-7 text-sm">{topic.content}</article></TabsContent>
      <TabsContent value="understand" className="mt-5 grid gap-3 md:grid-cols-3">{[["brain","Logic",hint[0]],["scan-line","Dry run",hint[1]],["gauge","Complexity",hint[2]]].map(([icon, title, content]) => <div key={title} className="rounded-xl border bg-background p-4"><Icon name={icon} className="h-5 w-5 text-primary mb-3" /><h3 className="font-semibold mb-1">{title}</h3><p className="text-sm text-muted-foreground leading-6">{content}</p></div>)}<div className="md:col-span-3 rounded-xl border border-streak/25 bg-streak/5 p-4 text-sm"><b className="flex items-center gap-2"><Icon name="lightbulb" className="h-4 w-4 text-streak" /> Important interview note</b><p className="text-muted-foreground mt-1">Explain your brute-force approach first, why it is too slow, and the exact pattern that removes repeated work. Good reasoning earns credit even before the final code.</p></div></TabsContent>
      <TabsContent value="practice" className="mt-5 space-y-3">{!topic.practiceLinks?.length ? <div className="rounded-xl border border-dashed p-5 text-sm text-muted-foreground">Practice questions are being curated for this lesson.</div> : topic.practiceLinks.map((p, i) => { const isSolved = solved.includes(p.url); return <div className="flex gap-3 rounded-xl border bg-background p-3 sm:items-center" key={p.url}><button onClick={() => toggle(p.url)} className={cn("h-6 w-6 rounded-full border shrink-0 flex items-center justify-center", isSolved ? "bg-success border-success text-white" : "text-transparent border-muted-foreground/40")}><Icon name="check" className="h-4 w-4" /></button><div className="flex-1"><div className={cn("font-medium text-sm", isSolved && "line-through text-muted-foreground")}>{i + 1}. {p.title}</div><div className="text-xs text-muted-foreground">{p.difficulty} · Make a dry run, then mark solved.</div></div><a href={p.url} target="_blank" rel="noreferrer"><Button size="sm" variant="outline">Solve <Icon name="arrow-up-right" className="ml-1 h-3.5 w-3.5" /></Button></a></div>; })}</TabsContent>
      <TabsContent value="notes" className="mt-5"><label className="text-sm font-medium">Your revision notes</label><p className="text-xs text-muted-foreground mt-1 mb-3">Automatically saved in this browser.</p><textarea value={notes} onChange={(e) => { setNotes(e.target.value); localStorage.setItem(notesKey, e.target.value); }} rows={9} placeholder="Pattern, edge cases, your mistake, final complexity…" className="w-full rounded-xl border bg-background p-3 text-sm leading-6 focus:outline-none focus:ring-2 focus:ring-primary/40" /></TabsContent></Tabs>
      <div className="flex flex-wrap gap-3 mt-6 pt-5 border-t"><Link to={`/app/tutor?topic=${encodeURIComponent(topic.title)}`}><Button variant="outline"><Icon name="sparkles" className="mr-2 h-4 w-4" /> Ask AI tutor</Button></Link>{enrolled && !done && <Button onClick={complete}><Icon name="check" className="mr-2 h-4 w-4" /> Complete lesson</Button>}</div></div>
  </section>;
}

export default function CourseDetail() {
  const { id } = useParams(); const qc = useQueryClient(); const [selectedId, setSelectedId] = useState(null);
  const { data, isLoading } = useQuery({ queryKey: ["course", id], queryFn: async () => (await api.get(`/courses/${id}`)).data });
  const enroll = async () => { try { await api.post(`/courses/${id}/enroll`); toast.success("Enrolled! Your workspace is ready."); qc.invalidateQueries({ queryKey: ["course", id] }); qc.invalidateQueries({ queryKey: ["courses"] }); } catch (_) { toast.error("Could not enroll"); } };
  const markComplete = async (topicId) => { try { const { data: res } = await api.post(`/courses/${id}/topic/${topicId}/complete`); toast.success(res.progress.progressPct >= 100 ? "Course complete! 🎉" : "Lesson completed · XP earned"); qc.invalidateQueries({ queryKey: ["course", id] }); qc.invalidateQueries({ queryKey: ["dashboard"] }); } catch (_) { toast.error("Action failed"); } };
  if (isLoading || !data) return <Loader />;
  const { course, topics, progress, enrolled } = data, done = new Set((progress?.completedTopics || []).map(String)), selected = topics.find((t) => String(t._id) === String(selectedId)) || topics[0];
  return <div><Link to="/app/courses" className="inline-flex items-center gap-1.5 text-sm text-muted-foreground hover:text-foreground mb-5"><Icon name="arrow-left" className="h-4 w-4" /> Back to learning hub</Link><div className="course-hero rounded-2xl overflow-hidden border mb-8 relative">{course.thumbnail && <img src={course.thumbnail} alt="" className="h-64 w-full object-cover opacity-35" />}<div className="absolute inset-0 bg-gradient-to-r from-background via-background/90 to-background/30" /><div className="absolute inset-0 p-6 sm:p-8 flex flex-col justify-end"><div className="eyebrow text-primary mb-2">{course.category} · {course.level}</div><h1 className="font-display text-3xl sm:text-4xl font-extrabold">{course.title}</h1><p className="text-muted-foreground mt-2 max-w-2xl">{course.description}</p><div className="flex flex-wrap gap-2 mt-4">{course.tags?.map((tag) => <Badge key={tag} variant="outline">{tag}</Badge>)}<Badge className="bg-ai/10 border-ai/20 text-ai">Interactive workspace</Badge></div></div></div>
  <div className="grid lg:grid-cols-3 gap-6"><div className="lg:col-span-2"><div className="flex justify-between items-end gap-3 mb-4"><div><h2 className="font-display text-xl font-semibold">Learning path</h2><p className="text-sm text-muted-foreground">Open a module to watch, understand and practise it.</p></div><span className="text-sm text-muted-foreground">{topics.length} modules</span></div><div className="space-y-2">{topics.map((t, i) => { const isDone = done.has(String(t._id)), active = String(selected?._id) === String(t._id); return <button key={t._id} onClick={() => setSelectedId(t._id)} className={cn("card-surface p-4 flex gap-4 items-center w-full text-left", isDone && "border-success/40", active && "ring-2 ring-primary/30 border-primary/50")}><div className={cn("h-9 w-9 rounded-lg flex items-center justify-center", isDone ? "bg-success/10 text-success" : "bg-primary/10 text-primary")}><Icon name={isDone ? "check" : typeIcon[t.type] || "book-open"} className="h-4 w-4" /></div><div className="flex-1"><div className="font-medium">{i + 1}. {t.title}</div><div className="text-xs text-muted-foreground">{t.durationMin} min · {t.practiceLinks?.length || 0} placement questions</div></div><Icon name="chevron-right" className="h-4 w-4 text-muted-foreground" /></button>; })}</div>{selected && <Workspace topic={selected} enrolled={enrolled} done={done.has(String(selected._id))} complete={() => markComplete(selected._id)} />}</div><aside><div className="card-surface p-6 sticky top-24">{enrolled ? <><div className="text-sm text-muted-foreground mb-1">Your progress</div><div className="font-display text-3xl font-bold mb-3">{progress.progressPct}%</div><Progress value={progress.progressPct} className="h-2 mb-4" /><p className="text-sm text-muted-foreground">{done.size} of {topics.length} modules completed.</p></> : <><div className="font-display text-lg font-semibold mb-2">Ready to start?</div><p className="text-sm text-muted-foreground mb-4">Enroll to save progress and earn XP as you learn.</p><Button className="w-full" onClick={enroll}>Enroll for free</Button></>}<div className="mt-6 pt-6 border-t space-y-3 text-sm text-muted-foreground"><div className="flex gap-2"><Icon name="video" className="h-4 w-4" /> Video lessons</div><div className="flex gap-2"><Icon name="brain" className="h-4 w-4" /> Logic & dry runs</div><div className="flex gap-2"><Icon name="target" className="h-4 w-4" /> Curated practice</div></div></div></aside></div></div>;
}
